<a href="https://colab.research.google.com/github/ALOUKIKA576/MLworkshop/blob/main/MLassignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1.Perform arthimetic operations on Numpy Arrays

In [ ]:
import numpy as np

##Addition


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


##subtraction

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a-b)

[-3 -3 -3]


##multiplication

In [ ]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x*y)

[[ 5 12]
 [21 32]]


##Division


In [ ]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


#2.Write a script to compute the mean and standard deviation of Numpy array

In [ ]:
a=np.array([1,2,3,4,5])
mean=np.mean(a,dtype=np.int64)
print("mean:",mean)
std_dev=np.std(a)
print("standard deviation:",std_dev)


mean: 3
standard deviation: 1.4142135623730951


#3.Create a NumPy array of integers from 10 to 50 with a step size of 5.

In [ ]:
a=np.arange(10,51,5)
print(a)

[10 15 20 25 30 35 40 45 50]


#4. Reshape the array into a 2x4 matrix.

In [ ]:
a=np.array([1,2,3,4,5,6,7,8])
print(a.reshape(2,4))

[[1 2 3 4]
 [5 6 7 8]]


#5. Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
• Extract the sub-matrix containing the last two rows and first two columns.

• Replace all elements greater than 4 with 0.


In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[1:,:2])

[[4 5]
 [7 8]]


#Create two 1D arrays:
• a = np.array([1, 2, 3])

• b = np.array([4, 5, 6])

• Perform element-wise addition, multiplication, and division.

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


#7. Create a random NumPy array of size (4, 4). Compute:
• Mean of each column.

• Maximum value of the entire array.

• Sum of all elements.

In [ ]:
import numpy as np
e = np.random.randint(1,101,size=(4,4))
print(e)
mean=np.mean(e,axis=1)
print(mean)
max=np.max(e)
print(max)
sum=np.sum(e)
print(sum)

[[84 19 93 12]
 [95 52 93  7]
 [89  3 59 22]
 [64 78  8 16]]
[52.   61.75 43.25 41.5 ]
95
794


#8. Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply the result by 2

In [ ]:
arr=np.array([1,2,3,4])
result=arr+10
print(result)
print(result*2)

[11 12 13 14]
[22 24 26 28]


#9. Perform advanced slicing and indexing on a 3D array.
Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from
1 to 100. Perform the following:

• Extract the second "layer" (i.e., the second 2D array) in the first dimension.

• Extract the first two rows and the last three columns from each "layer."

• Replace all elements divisible by 3 with -1.

In [ ]:
import numpy as np
arr=np.random.randint(1,101,size=(3,4,5))
print(arr)
a=arr[1,:,:]
print(a)
b=arr[:,:2,-3:]
print(b)
arr[arr%3==0]=-1
print(arr)



[[[68 63 70 74 57]
  [32 27 19 46 82]
  [72 33  8 85  7]
  [89 36 13 22  9]]

 [[85 84 22 61  2]
  [65  4  3 87  4]
  [15 55 18 97 96]
  [78 69 79 92 74]]

 [[84 27 57 81 74]
  [93  1 44 50 30]
  [79 79 96 82  6]
  [17 54 39 63 50]]]
[[85 84 22 61  2]
 [65  4  3 87  4]
 [15 55 18 97 96]
 [78 69 79 92 74]]
[[[70 74 57]
  [19 46 82]]

 [[22 61  2]
  [ 3 87  4]]

 [[57 81 74]
  [44 50 30]]]
[[[68 -1 70 74 -1]
  [32 -1 19 46 82]
  [-1 -1  8 85  7]
  [89 -1 13 22 -1]]

 [[85 -1 22 61  2]
  [65  4 -1 -1  4]
  [-1 55 -1 97 -1]
  [-1 -1 79 92 74]]

 [[-1 -1 -1 -1 74]
  [-1  1 44 50 -1]
  [79 79 -1 82 -1]
  [17 -1 -1 -1 50]]]


#10.Work with broadcasting and advanced operations in NumPy.

 Create a NumPy array arr of shape (3, 3) with random integers between
 1 and 20. Perform the following:

• Subtract the mean of each row from its respective elements (row-wise
normalization).

• Create a new array by squaring all the elements in arr.

• Find the indices of the top 3 maximum values in the entire arra

In [ ]:
import numpy as np
arr = np.random.randint(1, 21, size=(3, 3))
print(arr)
row_means = np.mean(arr, axis=1, keepdims=True)
normalized_arr = arr - row_means
print(normalized_arr)
squared_arr = np.square(arr)
print(squared_arr)
flattened_arr = arr.flatten()
top_3_indices = np.argsort(flattened_arr)[-3:]
top_3_2d_indices = np.unravel_index(top_3_indices, arr.shape)
print(top_3_2d_indices)


[[12 19  4]
 [ 8 16 10]
 [18 13  9]]
[[ 0.33333333  7.33333333 -7.66666667]
 [-3.33333333  4.66666667 -1.33333333]
 [ 4.66666667 -0.33333333 -4.33333333]]
[[144 361  16]
 [ 64 256 100]
 [324 169  81]]
(array([1, 2, 0]), array([1, 0, 1]))
